name: deploy to ConoHa WING

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable
      - name: Install mdBook
        run: cargo install mdbook
      - name: ssh key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avz --delete
          path: book/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
